apiVersion: v1
kind: Service
metadata:
  name: prometheus-eks-monitoring-sample-service
  namespace: default
  labels:
    app: prometheus-eks-monitoring-sample-app
spec:
  selector:
    app: prometheus-eks-monitoring-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP